"""create tankers table

Revision ID: 1bad295061ec
Revises: 5ee7cedd4e71
Create Date: 2026-06-08 02:13:43.677609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad295061ec'
down_revision: Union[str, None] = '5ee7cedd4e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tankers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=False),
    sa.Column('capacity_litres', sa.Integer(), nullable=False),
    sa.Column('default_source_id', sa.Uuid(), nullable=True),
    sa.Column('license_documents', sa.String(length=255), nullable=False),
    sa.Column('tanker_image', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_source_id'], ['water_sources.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_index(op.f('ix_tankers_id'), 'tankers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tankers_id'), table_name='tankers')
    op.drop_table('tankers')
    # ### end Alembic commands ###
