"""add_regulated_pricing

Revision ID: 60db122231d1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-20 08:12:03.225357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60db122231d1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('water_cost', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('transit_cost', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('distance_km', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('water_sources', sa.Column('price_per_litre', sa.Float(), server_default='2.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_sources', 'price_per_litre')
    op.drop_column('orders', 'distance_km')
    op.drop_column('orders', 'transit_cost')
    op.drop_column('orders', 'water_cost')
    # ### end Alembic commands ###
