"""create_ratings_table

Revision ID: 6404927475c9
Revises: 36f7b69caadf
Create Date: 2026-06-15 09:23:21.982771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6404927475c9'
down_revision: Union[str, None] = '36f7b69caadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('water_source_id', sa.Uuid(), nullable=False),
    sa.Column('rating_water_quality', sa.Integer(), nullable=False),
    sa.Column('rating_delivery_speed', sa.Integer(), nullable=False),
    sa.Column('rating_driver_professionalism', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['water_source_id'], ['water_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_customer_id'), 'ratings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ratings_driver_id'), 'ratings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_order_id'), 'ratings', ['order_id'], unique=True)
    op.create_index(op.f('ix_ratings_water_source_id'), 'ratings', ['water_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_water_source_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_order_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_driver_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_customer_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
